[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node server/server.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
SERVICE_NAME = "vitana-gestao-sistema"